Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kcoreaddons' : '@same'
    'frameworks/kwindowsystem' : '@same'

Options:
  test-before-installing: True
