Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kcoreaddons': '@same'

Options:
 test-before-installing: true
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
